# Generated by Django 5.2.6 on 2026-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_stock_quantity_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to='store/product/'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
