# Generated by Django 5.2.6 on 2026-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image_url_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='product_img/default.jpg', null=True, upload_to='product_img/'),
        ),
    ]
