# Generated by Django 5.2.6 on 2026-02-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='store.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'valid_from'], name='store_produ_product_1615be_idx'), models.Index(fields=['product', 'valid_to'], name='store_produ_product_e07638_idx')],
            },
        ),
    ]
