# Generated by Django 5.2.6 on 2026-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_price_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='follow_up_code',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='product_img/Asset_64x.png', null=True, upload_to='product_img/'),
        ),
    ]
