# Generated by Django 5.2.6 on 2026-02-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_options_alter_order_follow_up_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order'},
        ),
    ]
