# Generated by Django 5.2.6 on 2026-02-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_payment_user_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='follow_up_code',
            field=models.BigIntegerField(editable=False),
        ),
    ]
