version: "3.9"

services:
  db:
    image: postgres:15
    container_name: leather_db
    restart: always
    environment:
      POSTGRES_DB: leatherdb
      POSTGRES_USER: pstgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: leather_backend
    command: gunicorn LeatherStore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DB_NAME=leatherdb
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: