# Generated by Django 5.2.6 on 2026-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Administrator'), ('SITE_ADMIN', 'Site Administrator')], default=None, max_length=20, null=True),
        ),
    ]
